const FILES=['00-intro.md','01-muc-luc.md','02-tong-quan.md','03-buoi-1.md','04-buoi-2.md','05-buoi-3.md','06-buoi-4.md','07-buoi-5.md','08-mini-project.md','09-bai-tap.md','10-checklist-debug.md','11-bang-ghi-nho.md','12-cau-hoi-tu-on.md','13-ke-hoach-on-tap.md','14-checklist-cuoi.md'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),1800)};

function universalCssDemo(css){return `<!doctype html><html><head><meta name="viewport" content="width=device-width"><style>body{font-family:Arial,sans-serif;padding:22px;color:#222}.container,.parent,.product-list,.project-list,.navbar,.nav-list{border:1px dashed #bbb;padding:14px;margin:10px 0}.container,.product-list,.project-list,.navbar,.nav-list{display:flex;gap:10px}.item,.box,.child,.card,.project-card,.product-card{padding:12px;background:#eef2ff;border:1px solid #cbd5e1}.product-card{position:relative;width:230px}.product-card__badge,.badge{position:absolute;top:8px;right:8px;padding:4px 8px;background:#ef4444;color:#fff;border-radius:999px}.highlight,.message,.note{padding:8px}.nav-list{list-style:none}.demo-space{height:70px}${css}</style></head><body><div class="navbar"><b class="logo">Logo</b><ul class="nav-list"><li>Trang chủ</li><li>Dự án</li><li>Liên hệ</li></ul></div><main class="container"><div class="item">Item 1</div><div class="item">Item 2</div><div class="item">Item 3</div></main><h1 id="main-title">Tiêu đề mẫu</h1><p id="welcome" class="highlight message note">Nội dung mẫu để quan sát CSS.</p><div class="parent box"><div class="child">Child</div></div><article class="product-card card"><span class="product-card__badge badge">-20%</span><h3>Sản phẩm</h3><p>490.000đ</p><button>Mua ngay</button></article><div class="demo-space"></div><a href="#">Liên kết mẫu</a></body></html>`}
function makePreview(code,lang){if(lang==='html'||lang==='xml')return `<!doctype html><html><head><meta name="viewport" content="width=device-width"><style>body{font-family:Arial,sans-serif;padding:20px;line-height:1.5}img{max-width:100%}</style></head><body>${code}</body></html>`;if(lang==='css')return universalCssDemo(code);return `<!doctype html><html><body style="font-family:Arial;padding:20px"><p>Ví dụ <b>${esc(lang||'code')}</b> này dùng để đọc và phân tích code.</p></body></html>`}
function upgradeCode(){let n=0;$$('.chapter pre > code').forEach(code=>{if(code.closest('.code-lab'))return;n++;const pre=code.parentElement,lang=(code.className.match(/language-([\w-]+)/)||[])[1]||'code',raw=code.textContent;try{if(window.hljs)hljs.highlightElement(code)}catch{}const lab=document.createElement('div');lab.className='code-lab';lab.innerHTML=`<div class="code-toolbar"><div class="code-meta"><span class="lang-pill">${esc(lang)}</span><small>#${String(n).padStart(3,'0')}</small></div><div class="code-actions"><button class="code-action copy-btn" type="button">Copy</button><button class="code-action run-btn" type="button">Chạy ví dụ</button></div></div><div class="code-slot"></div><div class="output-panel" hidden><div class="output-toolbar"><span>OUTPUT</span><div class="viewport-tools"><button data-w="375">Mobile</button><button data-w="768">Tablet</button><button data-w="full" class="active">Desktop</button></div></div><div class="frame-stage"><div class="frame-shell"><iframe sandbox="allow-same-origin" title="Output ví dụ ${n}"></iframe></div></div></div>`;pre.replaceWith(lab);lab.querySelector('.code-slot').appendChild(pre);lab.querySelector('.copy-btn').onclick=async()=>{await navigator.clipboard.writeText(raw);toast('Đã copy code')};lab.querySelector('.run-btn').onclick=()=>{const panel=lab.querySelector('.output-panel'),frame=lab.querySelector('iframe');panel.hidden=!panel.hidden;if(!panel.hidden)frame.srcdoc=makePreview(raw,lang)};lab.querySelectorAll('[data-w]').forEach(b=>b.onclick=()=>{lab.querySelectorAll('[data-w]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const shell=lab.querySelector('.frame-shell');shell.style.maxWidth=b.dataset.w==='full'?'100%':b.dataset.w+'px'})})}
function enhanceHeadings(){const used=new Map();$$('.chapter h1,.chapter h2,.chapter h3').forEach(h=>{let id=slug(h.textContent),c=used.get(id)||0;used.set(id,c+1);if(c)id+=`-${c+1}`;h.id=id;const a=document.createElement('a');a.href='#'+id;a.textContent=' #';a.style.cssText='text-decoration:none;color:var(--muted);font-size:.45em';h.appendChild(a)});$$('.chapter').forEach((s,i)=>{const h=s.querySelector('h1');if(h)s.id='chapter-'+slug(h.childNodes[0].textContent.trim())})}
function buildNav(){const nav=$('#courseNav');nav.innerHTML='';$$('.chapter').filter(s=>/^\d+\./.test(s.querySelector('h1')?.childNodes[0]?.textContent.trim()||'')).forEach((s,i)=>{const title=s.querySelector('h1').childNodes[0].textContent.trim(),a=document.createElement('a');a.href='#'+s.id;a.dataset.target=s.id;a.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><b>${esc(title.replace(/^\d+\.\s*/,''))}</b>`;nav.appendChild(a)})}
function activateNav(){const secs=$$('.chapter').filter(s=>s.id),links=$$('#courseNav a');let current='';for(const s of secs)if(s.getBoundingClientRect().top<180)current=s.id;links.forEach(a=>a.classList.toggle('active',a.dataset.target===current))}
function progress(){const d=document.documentElement,den=d.scrollHeight-d.clientHeight,p=den?Math.min(100,Math.max(0,scrollY/den*100)):0;$('#scrollProgress').style.width=p+'%';$('#readBar').style.width=p+'%';$('#readPercent').textContent=Math.round(p)+'%';$('#backTop').classList.toggle('show',scrollY>600);activateNav()}
function setupSearch(){const input=$('#siteSearch');const run=()=>{const q=input.value.trim().toLowerCase();$$('.search-hit').forEach(x=>x.classList.remove('search-hit'));if(!q)return;const el=$$('.chapter h1,.chapter h2,.chapter h3,.chapter p,.chapter li').find(x=>x.textContent.toLowerCase().includes(q));if(el){el.classList.add('search-hit');el.scrollIntoView({behavior:'smooth',block:'center'});toast('Đã tìm thấy nội dung')}else toast('Không tìm thấy')};$('#searchBtn').onclick=run;input.addEventListener('keydown',e=>{if(e.key==='Enter')run()});document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea/i.test(e.target.tagName)){e.preventDefault();input.focus()}})}
function setupTheme(){const apply=v=>document.documentElement.dataset.theme=v;apply(localStorage.getItem('jsb-theme')||'light');const toggle=()=>{const v=document.documentElement.dataset.theme==='dark'?'light':'dark';apply(v);localStorage.setItem('jsb-theme',v)};$('#themeToggle').onclick=toggle;$('#themeToggleMobile').onclick=toggle}
function setupMobile(){const side=$('#sidebar'),scrim=$('#sidebarScrim'),close=()=>{side.classList.remove('open');scrim.classList.remove('show')};$('#menuToggle').onclick=()=>{side.classList.add('open');scrim.classList.add('show')};scrim.onclick=close;$('#courseNav').addEventListener('click',close);$('#backTop').onclick=()=>scrollTo({top:0,behavior:'smooth'})}
async function init(){try{if(!window.marked)throw new Error('Không tải được thư viện Markdown.');marked.setOptions({gfm:true,breaks:false});const texts=await Promise.all(FILES.map(async f=>{const r=await fetch('./content/'+f);if(!r.ok)throw new Error(`${f}: HTTP ${r.status}`);return r.text()}));const root=$('#course');root.innerHTML=texts.map((md,i)=>`<section class="chapter" data-file="${FILES[i]}">${marked.parse(md)}</section>`).join('\n');enhanceHeadings();upgradeCode();buildNav();setupSearch();setupTheme();setupMobile();addEventListener('scroll',progress,{passive:true});progress()}catch(e){console.error(e);$('#course').innerHTML=`<div class="error-box"><h2>Không tải được tài liệu</h2><p>Hãy chạy bằng Live Server hoặc GitHub Pages.</p><pre>${esc(String(e.message||e))}</pre></div>`}}
init();
